# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'
# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# target 'NativeReactIOS' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   use_react_native!
#   # Pods for NativeReactIOS

#   # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

#   target 'NativeReactIOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

#   target 'NativeReactIOSUITests' do
#     # Pods for testing
#   end

# end
# # target 'NativeReactMac' do
# #   # Comment the next line if you don't want to use dynamic frameworks
# #   use_frameworks!
# #   use_react_native!
# #   # Pods for NativeReactIOS

# #   # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

# # end


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# target 'NativeReactMac-macOS' do
#   platform :macos, '10.15'
#   use_native_modules!
#   use_react_native!(
#     :path => '../node_modules/react-native',
#     # to enable hermes on macOS, change `false` to `true` and then install pods
#     :hermes_enabled => false
#   )

#   # Pods specifically for macOS target
# end

target 'NativeReactIOS' do
  platform :ios, '13.0'
  use_native_modules!
  use_react_native!(:path => '../node_modules/react-native')

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  use_flipper!

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  # Pods specifically for iOS target
end

